### ISSUE TITLE
runs `npm run build` after installation

### ISSUE THREAD

**Issue by mechanical-turk** [prescottprue/redux-firestore#1]
For some reason, installing `redux-firestore` will run `npm run build` immediately after installation. That results in the failure of the installation. I was trying to install it in a create-react-app project, and there was already a build script in my package.json. I temporarily removed that script from my package.json, and the install was successful. So I think that there's some sort of interference between the build script that `redux-firestore` calls, and the one that exists in the root project's package.json.

**Comment by mechanical-turk** [comment]
Shouldnt we just build it first and then distribute the code? Is this something we are doing to increase compatibility? Because it seems to be decreasing compatibility in my case. Because in order to be able to build the library, it seems that we need to have the `cross-env` script installed globally.

Even when you install the cross-env script, building fails with the following error: 
```
Error: spawn babel ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

So I suggest that we build first and then distribute the library, because all these dependencies that are required to be able to build the library seem to be getting in the way. What do you think @prescottprue?

**Comment by mechanical-turk** [comment]
The issue was partially solved in the latest push.
